apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argo
  annotations:
    argocd-image-updater.argoproj.io/image-list: 'stefanprodan/podinfo:~6.5.0'
spec:
  project: default
  source:
    repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/gitea/infra.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: app