replicaCount: 2

image:
  repository: stefanprodan/podinfo
  tag: "6.6.2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9898

resources:
  limits:
    cpu: 200m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}